/* Run with: node tests/playlist_matching_gui.cjs (requires jsdom). */
const assert = require('node:assert/strict');
const fs = require('node:fs');
const { JSDOM } = require('jsdom');
const html = fs.readFileSync('app/templates/playlist.html', 'utf8');
const start = html.indexOf('async function editCustomChannel(id)');
const end = html.indexOf('/* ============================ VOD builder', start);
assert.ok(start >= 0 && end > start);
const dom = new JSDOM('<body></body>', {runScripts:'outside-only', url:'http://localhost/'});
const w = dom.window, d = w.document;
const requests = [], notifications = [];
let reloads = 0, modal;
w.$ = (s, root=d) => root.querySelector(s);
w.el = (tag, attrs={}, ...children) => {
  const e = d.createElement(tag);
  for (const [key, value] of Object.entries(attrs)) e.setAttribute(key, value);
  e.append(...children); return e;
};
w.esc = value => { const e = d.createElement('span'); e.textContent=value ?? ''; return e.innerHTML; };
w.mBtn = (text, cls, action) => {
  const b = w.el('button', {type:'button', class:cls}, text);
  b.addEventListener('click', action); return b;
};
w.toast = (...args) => notifications.push(args);
w.api = (url, options) => new Promise((resolve, reject) => requests.push({url, options, resolve, reject}));
w.openModal = ({body, footer, onClose}) => {
  const container = w.el('div', {}, body, footer); d.body.append(container);
  modal = {body, footer, close() { onClose?.(); container.remove(); }};
  return modal;
};
w.liveTable = {items:[{id:9, custom_name:'NPO 1', chain:[{source_id:77, name:'Existing source', portal:'Original portal'}]}],
  reload: async () => ++reloads};
w.groupDialogHtml = (id, value) => `<input id="${id}" value="${w.esc(value)}">`;
w.tplOptions = () => '<option value="">Default</option>';
w.eval(html.slice(start, end));
const tick = () => new Promise(resolve => setTimeout(resolve, 10));
const findButton = (root, label) => [...root.querySelectorAll('button')].find(b => b.textContent === label);
const loose = {id:7, name:'NL NPO1 Netherlands HEVC 1080p', portal:'Test portal', logo:null};
const toggle = checked => { w.$('#cc-relaxed').checked=checked; w.$('#cc-relaxed').dispatchEvent(new w.Event('change')); };
const params = request => new URL(request.url, 'http://localhost').searchParams;
(async () => {
  await w.editCustomChannel(9);
  assert.equal(w.$('#cc-relaxed').checked, false);
  assert.match(w.$('label[for="cc-relaxed"]').title, /weaker name matches/);
  assert.equal(params(requests[0]).get('relaxed'), 'false');
  requests[0].resolve({items:[]}); await tick();
  findButton(w.$('#cc-cand'), 'Try less strict matching').click();
  assert.equal(w.$('#cc-relaxed').checked, true);
  assert.equal(params(requests[1]).get('relaxed'), 'true');
  assert.equal(params(requests[1]).get('q'), 'NPO 1');
  assert.match(w.$('#cc-chain').textContent, /Existing source/);

  // An older relaxed response must not overwrite a newer strict search.
  toggle(false);
  requests[2].resolve({items:[]}); await tick();
  requests[1].resolve({items:[{...loose, name:'Outdated result'}]}); await tick();
  assert.doesNotMatch(w.$('#cc-cand').textContent, /Outdated result/);
  toggle(true); requests[3].resolve({items:[loose]}); await tick();
  assert.match(w.$('#cc-count').textContent, /1 matches \(less strict\)/);
  assert.equal(w.$('#cc-cand').getAttribute('aria-busy'), 'false');
  w.$('#cc-cand button').click(); w.$('#cc-cand button').click();
  assert.equal(w.$('#cc-chain').children.length, 2);
  assert.equal(notifications.at(-1)[0], 'already in chain');
  assert.equal(w.$('#cc-name').value, 'NPO 1');
  toggle(false); requests[4].resolve({items:[]}); await tick();
  assert.equal(w.$('#cc-chain').children.length, 2);
  findButton(modal.footer, 'Save').click();
  const save = requests[5];
  assert.equal(save.url, '/api/playlist/live/9');
  assert.deepEqual(Array.from(save.options.body.source_ids), [77, 7]);
  assert.equal(save.options.body.custom_name, 'NPO 1');
  assert.equal('relaxed' in save.options.body, false);
  save.resolve({}); await tick();
  assert.equal(reloads, 1);

  // Reopening defaults to strict. Failures are visible and retryable.
  await w.editCustomChannel(9);
  assert.equal(w.$('#cc-relaxed').checked, false);
  requests[6].reject(new Error('Test failure')); await tick();
  assert.match(w.$('#cc-cand').textContent, /Could not load source channels: Test failure/);
  findButton(w.$('#cc-cand'), 'Retry').click();
  w.$('#cc-name').value = 'New query';
  w.$('#cc-name').dispatchEvent(new w.Event('input'));
  requests[7].resolve({items:[{...loose, name:'Old name result'}]}); await tick();
  assert.doesNotMatch(w.$('#cc-cand').textContent, /Old name result/);
  modal.close();
  await new Promise(resolve => setTimeout(resolve, 300));
  assert.equal(requests.length, 8, 'closing cancels a debounced request');
  // Browse every source and search independently from the custom channel name.
  requests.length = 0;
  await w.editCustomChannel(9);
  assert.equal(w.$('#cc-show-all').checked, false);
  assert.equal(w.$('#cc-source-filter-wrap').hidden, true);
  requests[0].resolve({items:[]}); await tick();
  toggle(true); requests[1].resolve({items:[loose]}); await tick();
  const showAll = checked => {
    w.$('#cc-show-all').checked = checked;
    w.$('#cc-show-all').dispatchEvent(new w.Event('change'));
  };
  showAll(true);
  assert.equal(w.$('#cc-relaxed').disabled, true);
  assert.equal(w.$('#cc-source-filter-wrap').hidden, false);
  assert.equal(params(requests[2]).get('show_all'), 'true');
  assert.equal(params(requests[2]).get('q'), 'NPO 1');
  const other = {...loose, id:8, name:'Unrelated channel'};
  requests[2].resolve({items:[other], total:3, next_offset:1}); await tick();
  assert.equal(w.$('#cc-count').textContent, '1 of 3 sources');
  assert.equal(w.$('#cc-load-more').hidden, false);
  w.$('#cc-cand button').click();
  w.$('#cc-load-more').click();
  assert.equal(params(requests[3]).get('offset'), '1');
  requests[3].reject(new Error('Page failed')); await tick();
  findButton(w.$('#cc-cand'), 'Retry').click();
  assert.equal(params(requests[4]).get('offset'), '1');
  requests[4].resolve({items:[loose], total:3, next_offset:2}); await tick();
  assert.equal(w.$('#cc-cand').children.length, 2);
  assert.equal(w.$('#cc-count').textContent, '2 of 3 sources');
  assert.match(w.$('#cc-chain').textContent, /Unrelated channel/);
  w.$('#cc-load-more').click();
  const filter = w.$('#cc-source-filter');
  filter.value = 'News TEST'; filter.dispatchEvent(new w.Event('input'));
  requests[5].resolve({items:[{...other, id:10, name:'Stale page'}], total:3, next_offset:null});
  await tick();
  assert.doesNotMatch(w.$('#cc-cand').textContent, /Stale page/);
  await new Promise(resolve => setTimeout(resolve, 270));
  assert.equal(params(requests[6]).get('source_filter'), 'News TEST');
  assert.equal(params(requests[6]).get('offset'), '0');
  requests[6].resolve({items:[{...other, id:9, name:'Independent News'}], total:1, next_offset:null});
  await tick();
  assert.equal(w.$('#cc-count').textContent, '1 of 1 sources');
  assert.equal(w.$('#cc-load-more').hidden, true);
  assert.equal(w.$('#cc-cand').children.length, 1);
  w.$('#cc-cand button').click();
  assert.equal(w.$('#cc-name').value, 'NPO 1');
  showAll(false);
  assert.equal(w.$('#cc-relaxed').disabled, false);
  assert.equal(w.$('#cc-relaxed').checked, true);
  assert.equal(w.$('#cc-source-filter-wrap').hidden, true);
  assert.equal(params(requests[7]).get('show_all'), 'false');
  requests[7].resolve({items:[loose]}); await tick();
  assert.equal(w.$('#cc-chain').children.length, 3);
  findButton(modal.footer, 'Save').click();
  assert.equal(requests[8].options.body.custom_name, 'NPO 1');
  assert.deepEqual(Array.from(requests[8].options.body.source_ids), [77, 8, 9]);
  assert.equal('show_all' in requests[8].options.body, false);
  assert.equal('source_filter' in requests[8].options.body, false);
  requests[8].resolve({}); await tick();
  await w.editCustomChannel(9);
  assert.equal(w.$('#cc-show-all').checked, false);
  assert.equal(w.$('#cc-source-filter').value, '');
  assert.equal(w.$('#cc-relaxed').checked, false);
  modal.close(); requests[9].resolve({items:[loose]}); await tick();
  dom.window.close();
  console.log('Channel matching: all-source browsing, free-text filtering, paging/retries, stale pages, name/chain/save preservation passed.');
  console.log('Channel matching: strict default, empty-state broadening, mode/race handling, chain/save preservation and retries passed.');
})().catch(error => { console.error(error); dom.window.close(); process.exitCode=1; });
