// Optional DOM regression: node tests/portal_resolve_gui.cjs (requires jsdom).
const assert = require('node:assert/strict');
const fs = require('node:fs');
const {JSDOM} = require('jsdom');
const dom = new JSDOM('<body></body>', {runScripts:'outside-only'});
const w = dom.window;
w.$ = (q, root = w.document) => root.querySelector(q);
w.$$ = (q, root = w.document) => [...root.querySelectorAll(q)];
w.el = (tag, attrs = {}) => {
  const node = w.document.createElement(tag);
  Object.entries(attrs).forEach(([key,value]) => node.setAttribute(key,value));
  return node;
};
w.esc = value => { const n = w.el('span'); n.textContent = value ?? ''; return n.innerHTML; };
w.openModal = ({body,footer}) => {
  const root = w.el('div'); root.append(body,footer); w.document.body.append(root);
  return {close:() => root.remove()};
};
w.mBtn = (text, cls, fn) => { const b = w.el('button'); b.textContent = text; b.onclick = fn; return b; };
w.xtreamHtml = () => '';
w.loadGenres = async () => {};
w.toast = () => {};
w.table = {items:[], reload:() => { throw Error('Resolve must not save/reload a portal'); }};
const requests = [];
w.api = (url, options) => new Promise((resolve,reject) => requests.push({url,options,resolve,reject}));
const template = fs.readFileSync('app/templates/portals.html','utf8');
w.eval(template.slice(template.indexOf('async function editPortal(id)'), template.indexOf('/* Live client-side genre filter:')));
const node = id => w.document.getElementById(id);
const fill = (id,value) => { node(id).value = value; node(id).dispatchEvent(new w.Event('input',{bubbles:true})); };
const tick = () => new Promise(resolve => setImmediate(resolve));
(async () => {
  await w.editPortal();
  const button = node('p-resolve-btn');
  assert.equal(button.disabled,true);
  fill('p-url','https://draft.invalid/c/');
  fill('p-macs','00-1a-79-ab-cd-ef');
  assert.equal(button.disabled,true,'name is still missing');
  fill('p-name','Draft');
  assert.equal(button.disabled,false,'no save or database ID is required');
  fill('p-macs','invalid'); assert.equal(button.disabled,true);
  fill('p-macs','00:1A:79:AB:CD:EF'); assert.equal(button.disabled,false);
  button.click(); button.click();
  assert.equal(requests.length,1,'duplicate probes are blocked');
  assert.equal(requests[0].url,'/api/portals/resolve');
  assert.equal(requests[0].options.body.portal_id,null);
  assert.equal(requests[0].options.body.identity_mode,'minimal');
  assert.equal(requests[0].options.body.base_url,'https://draft.invalid/c/');
  fill('p-url','https://changed.invalid/c/');
  requests[0].resolve({ok:true,resolved_url:'https://old-result.invalid/'}); await tick();
  assert.equal(button.disabled,false);
  assert.match(node('p-resolve-out').textContent,/Details changed/);
  assert.ok(!node('p-resolve-out').textContent.includes('old-result'));
  button.click();
  assert.equal(requests[1].options.body.base_url,'https://changed.invalid/c/');
  requests[1].reject(new Error('network failure')); await tick();
  assert.match(node('p-resolve-out').textContent,/network failure/);
  assert.equal(button.disabled,false,'failure allows retry');
  button.click();
  requests[2].resolve({ok:true,resolved_url:'https://changed.invalid/c/portal.php'}); await tick();
  assert.match(node('p-resolve-out').textContent,/without saving/);
  assert.match(node('p-resolve-out').textContent,/changed.invalid/);
  [...w.document.querySelectorAll('button')].find(b => b.textContent === 'Cancel').click();

  w.table.items = [{id:7,name:'Saved',base_url:'http://saved.invalid/',macs:[{mac:'00:1A:79:AB:CD:EF'}],identity_mode:'minimal'}];
  await w.editPortal(7);
  assert.equal(node('p-resolve-btn').disabled,false);
  fill('p-url','https://unsaved.invalid/c/');
  fill('p-proxy','http://proxy.invalid:8080');
  fill('p-identity','mag250');
  fill('p-tz','Europe/Berlin');
  node('p-tls').checked = true;
  node('p-resolve-btn').click();
  assert.equal(requests[3].options.body.portal_id,7);
  assert.equal(requests[3].options.body.base_url,'https://unsaved.invalid/c/');
  assert.equal(requests[3].options.body.proxy_url,'http://proxy.invalid:8080');
  assert.equal(requests[3].options.body.identity_mode,'mag250');
  assert.equal(requests[3].options.body.stb_timezone,'Europe/Berlin');
  assert.equal(requests[3].options.body.tls_insecure,true);
  [...w.document.querySelectorAll('button')].find(b => b.textContent === 'Cancel').click();
  requests[3].resolve({ok:true,resolved_url:'http://late.invalid/'}); await tick();
  assert.equal(w.document.body.children.length,0,'closing does not resurrect a late result');
  console.log('Portal Resolve DOM checks passed: immediate activation, draft settings, no save, duplicate/stale guards, failure/retry and close.');
  dom.window.close();
})().catch(error => { console.error(error); dom.window.close(); process.exitCode = 1; });
