/* node tests/user_groups_gui.cjs (requires jsdom). */
const assert = require('node:assert/strict');
const fs = require('node:fs');
const {JSDOM} = require('jsdom');
const dom = new JSDOM('<body></body>', {runScripts:'outside-only'});
const w = dom.window;
w.$ = (q, root=w.document) => root.querySelector(q);
w.$$ = (q, root=w.document) => [...root.querySelectorAll(q)];
w.el = (tag, attrs={}) => {const node=w.document.createElement(tag); for(const [k,v] of Object.entries(attrs)) node.setAttribute(k,v); return node;};
w.esc = value => {const node=w.el('span'); node.textContent=value??''; return node.innerHTML;};
w.mBtn = (text,cls,fn) => {const b=w.el('button'); b.textContent=text; b.onclick=fn; return b;};
w.openModal = ({body,footer}) => { const root=w.el('div'); root.append(body,footer); w.document.body.append(root); return {close:()=>root.remove()}; };
w.toast = () => {};
w.AREAS = [];
w.GROUPS = {live:['News','Sport'],vod:['Action','Comedy'],series:['Drama','Kids'],local:['Files','Family']};
w.table = {items:[],reload:()=>{}};
const calls=[];
w.api = async (url, options) => {calls.push({url,options}); return {id:1};};
const html=fs.readFileSync('app/templates/users.html','utf8');
w.eval(html.slice(html.indexOf('window.editUser ='), html.indexOf('window.delUser =')));
const kinds=Object.keys(w.GROUPS);
const click = (action,kind) => w.$(`[data-${action}-groups="${kind}"]`).click();
const checked = kind => w.$$(`.g-${kind}`).filter(b=>b.checked).map(b=>b.value);
const save = () => [...w.document.querySelectorAll('button')].find(b=>b.textContent==='Save').click();
const tick = () => new Promise(resolve=>setImmediate(resolve));
(async () => {
  w.editUser(null);
  for (const kind of kinds) {
    assert.deepEqual(checked(kind), w.GROUPS[kind], 'new user selects every current group');
    assert.equal(w.$(`[data-select-groups="${kind}"]`).disabled, true);
    click('deselect',kind);
    assert.deepEqual(checked(kind), []);
    assert.match(w.$(`#gs-${kind}`).textContent,/0 \/ 2 selected/);
    assert.equal(w.$(`[data-deselect-groups="${kind}"]`).disabled, true);
    click('select',kind);
    assert.deepEqual(checked(kind), w.GROUPS[kind]);
  }
  w.$('.g-live').checked=false; w.$('.g-live').dispatchEvent(new w.Event('change'));
  assert.match(w.$('#gs-live').textContent,/1 \/ 2 selected/);
  assert.deepEqual(checked('vod'),w.GROUPS.vod,'a type control must not affect another list');
  for(const kind of kinds) click('deselect',kind);
  w.$('#u-name').value='test-user'; w.$('#u-pass').value='test-password';
  save(); await tick();
  const payload=JSON.parse(JSON.stringify(calls[0].options.body));
  assert.equal(calls[0].url,'/api/users');
  assert.deepEqual(payload.groups,{live:[],vod:[],series:[],local:[]});
  w.table.items=[{...payload,id:1}];
  w.editUser(1);
  for(const kind of kinds) assert.deepEqual(checked(kind), [], 'empty saved lists remain deselected on edit');
  click('select','local'); save(); await tick();
  assert.equal(calls[1].url,'/api/users/1');
  assert.deepEqual(JSON.parse(JSON.stringify(calls[1].options.body.groups)), {live:[],vod:[],series:[],local:['Files','Family']});
  w.table.items[0].groups={live:['Removed group'],vod:[],series:[],local:[]};
  w.editUser(1);
  assert.deepEqual(checked('live'),['Removed group']);
  click('deselect','live'); save(); await tick();
  assert.deepEqual(Array.from(calls[2].options.body.groups.live), [], 'deselect all also removes stale selections');
  w.GROUPS.local=[]; w.editUser(null);
  assert.equal(w.$('[data-select-groups="local"]').disabled,true);
  assert.equal(w.$('[data-deselect-groups="local"]').disabled,true);
  assert.match(w.$('#gs-local').textContent,/0 \/ 0 selected/);
  assert.ok(!html.includes('empty allows all'));
  assert.ok(html.includes('No selection means no groups of that type'));
  dom.window.close();
  console.log('User groups GUI passed: new defaults, per-type select/deselect, counts, empty save/reopen, stale selections, and no groups available.');
})().catch(error=>{console.error(error);dom.window.close();process.exitCode=1;});
